name: AD-EnKF-env
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py37haa95532_0
  - cudatoolkit=10.2.89=h74a9793_1
  - cycler=0.10.0=py37_0
  - freetype=2.10.4=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2021.3.0=haa95532_3372
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.3.1=py37hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - lz4-c=1.9.3=h2bbff1b_0
  - matplotlib=3.3.4=py37haa95532_0
  - matplotlib-base=3.3.4=py37h49ac443_0
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.0=py37h277e83a_2
  - mkl_random=1.2.2=py37hf11a4ad_0
  - ninja=1.10.2=h6d14046_1
  - numpy=1.20.3=py37ha4e8547_0
  - numpy-base=1.20.3=py37hc2deb75_0
  - olefile=0.46=py37_0
  - openssl=1.1.1k=h2bbff1b_0
  - pillow=8.3.1=py37h4fa10fc_0
  - pip=21.1.3=py37haa95532_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h6538335_2
  - python=3.7.10=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.9.0=py3.7_cuda10.2_cudnn7_0
  - qt=5.9.7=vc14h73c81de_0
  - scipy=1.6.2=py37h66253e8_1
  - setuptools=52.0.0=py37haa95532_0
  - sip=4.19.8=py37h6538335_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tk=8.6.10=he774522_0
  - torchaudio=0.9.0=py37
  - torchvision=0.10.0=py37_cu102
  - tornado=6.1=py37h2bbff1b_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py37_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - torchdiffeq==0.2.2
prefix: C:\Users\cheny\Anaconda3\envs\AD-EnKF-env
